### ISSUE TITLE
possible typo in documentation

### ISSUE THREAD

**Issue by gokhalen** [Pressio/pressio-demoapps#123]
Hi, 

Is there a possible typo in the documentation here: 

https://pressio.github.io/pressio-demoapps/apipy.html#Problem.totalDofStencilMesh

Shouldn't it be: 

```
# of dofs on stencil mesh = # dofs/cell times the # of STENCIL mesh cells.
```
instead of 
```
# of dofs on stencil mesh = # dofs/cell times the # of SAMPLE mesh cells.
```
Nachiket

**Comment by fnrizzi** [comment]
that it right! thanks for finding it!
