### ISSUE TITLE
add rankine-hugoniot function for determining pre/post-shock states

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio-demoapps#16]
- related to #6 
- function should accept prim vars on one side and return the prim on the other
- a test should be added to only test this function is correct

**Comment by fnrizzi** [comment]
@pjb236 in your latest pushed code, i don't see the Rank-Hug function file, did you forgot to stage it?

**Comment by pjb236** [comment]
Sorry, just pushed it.
