### ISSUE TITLE
add double Mach reflection

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio-demoapps#6]
References:
- https://homepages.dias.ie/jmackey/jmac/node10.html
- others? 

- [ ] problem setup: domain, BC, etc 

- [ ] add initial condition for the problem here: https://github.com/Pressio/pressio-demoapps/blob/main/include/impl/euler2d/initial_condition.hpp
- [ ] add Eigen implementation: 
  - file to use : https://github.com/Pressio/pressio-demoapps/blob/main/include/impl/euler2d/eigen_app.hpp
  - use a proper value for `probid` (see the other cases) to identify this particular problem 

- [x] add the public alias for this problem here: https://github.com/Pressio/pressio-demoapps/blob/main/include/euler.hpp

- [ ] add a test for it, use the Sedov test as template: https://github.com/Pressio/pressio-demoapps/tree/main/tests/sedov2d 
  - to create the mesh files, see python script [here](https://github.com/Pressio/pressio-demoapps/blob/main/meshing_scripts/create_full_mesh.py)
   If we use the domain in the reference above, the command is something: 
   ```py
   python create_full_mesh.py --outDir <where-youwant-the-mesh-files> \
   -s 7 --bounds 0.0 0.325 0.0 1.0 --periodic false -n 260 80
   ```
   the `-s 7` is to create a mesh with a 7 point stencil.

**Comment by pjb236** [comment]
For a Mach 10 shock in air, assuming a perfect gas, the following conditions need to be satisfied:

Index 1: in front of the shock
Index 2: behind the shock

pressure: p2/p1 = 116.5
density: rho2/rho1 =  5.714
temperature: T2/T1 = 20.39
Mach number: M2 = 0.3876

**Comment by pjb236** [comment]
@fnrizzi do you have an implementation of the reflecting BC I could work from?

**Comment by fnrizzi** [comment]
@pjb236 if you look at [this file](https://github.com/Pressio/pressio-demoapps/blob/windTunnelWithStep/include/impl/euler2d/eigen_app.hpp), lines 518 you see this: 
```c++
if (n0 == -1){ 
 const auto ind = cellGID*numDofPerCell_;
 ghostTop_(smPt, 0) = U[ind];	
 ghostTop_(smPt, 1) = U[ind+1];	
 ghostTop_(smPt, 2) = -U[ind+2];	
 ghostTop_(smPt, 3) = U[ind+3];      
}
```
which shows reflecting BC at the top boundary.

**Comment by pjb236** [comment]
It seems that the instability is due to the strong shock hitting an outflow BC at an angle. When the reflecting BC is changed to an outflow (Neumann) BC, the instability still occurs. When the shock angle is changed to zero and the shock is perpendicular to the bottom, no instability occurs. 

Also, it should be pointed out that weaker shocks (with smaller Mach number) do not encounter the same instability. 

Overall, this suggests that we need to look at our high order Neumann BC.

**Comment by fnrizzi** [comment]
- what do you mean by weaker shock? 
- is the code pushed?

**Comment by pjb236** [comment]
> * what do you mean by weaker shock? how much weaker? so for weaker shock things work?

A weaker shock is one with smaller jumps in pressures, density, etc. Yes, things work for this case. 

> * is the code pushed?

I did this study with slight modifications of the code currently in the repo. Specifically, the shock mach number and angle were modified in the following locations:

include/impl/euler2d/eigen_app.hpp: lines 515-516

include/impl/euler2d/initial_condition.hpp: lines 192-193

**Comment by fnrizzi** [comment]
which branch?

**Comment by pjb236** [comment]
I tried using a Dirichlet BC on the bottom of the domain. If I do this, then move the start of the wedge back from the shock's initial position, the simulation is stable until the the shock touches the wedge. I got this result for a 360 by 120 mesh.

**Comment by fnrizzi** [comment]
@pjb236 at some point, I need to update this to use the latest impl in develop. Let me know when I can do that!

**Comment by pjb236** [comment]
@fnrizzi go ahead and update it!

**Comment by fnrizzi** [comment]
working in develop, but WENO5 still to be fixed
